[project]
name = "python-skeleton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ryan McKeown", email = "ryanmckeown@mail4me.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
python-skeleton = "python_skeleton:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.7",
    "taplo>=0.9.3",
    "ty>=0.0.81",
]
docs = [
    "mkdocs-autoapi>=0.4.1",
    "mkdocs-include-markdown-plugin>=7.3.0",
    "mkdocs-shadcn>=0.12.1",
    "mkdocstrings-python>=2.0.8",
    "properdocs>=1.6.7",
]

[tool.ruff.format]
skip-magic-trailing-comma = true
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["ANN", "N818"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
