[project]
authors = [{ name = "Ryan McKeown", email = "ryanmckeown@mail4me.com" }]
dependencies = ["click>=8.5.0"]
description = "Add your description here"
name = "python-skeleton"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"

[project.scripts]
python-skeleton = "python_skeleton:cli.cli"

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.12.14,<0.13.0"]

[dependency-groups]
dev = [
    "docformatter>=1.7.8",
    "google-yamlfmt>=0.21.0",
    "pytest-cov>=7.1.0",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
    "rumdl>=0.2.73",
    "taplo>=0.9.3",
    "ty>=0.0.81",
    "yamllint>=1.38.0",
]
docs = [
    "mkdocs-autoapi>=0.4.1",
    "mkdocs-click>=0.9.0",
    "mkdocs-include-markdown-plugin>=7.3.0",
    "mkdocs-shadcn>=0.12.1",
    "mkdocstrings-python>=2.0.8",
    "properdocs>=1.6.7",
]

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint]
extend-select = ["ANN", "N818"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-glob=*.md --ignore=docs/scripts --ignore=site"
