name: Build
on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: build
  cancel-in-progress: false

jobs:

  deploy_docs:
    name: Deploy documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          email_domain="users.noreply.github.com"
          git config user.email "41898282+github-actions[bot]@$email_domain"
      - name: Deploy documentation
        run: uv run --frozen properdocs gh-deploy --force
