name: Continuous Integration
on: [pull_request]

permissions:
  contents: read
  code-quality: write

jobs:

  python_lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: Code linting check
        run: uv run --frozen ruff check --output-format=github .

  python_format:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: Code formatting check
        run: uv run --frozen ruff format --diff .

  python_type_check:
    name: Code type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: Code type checking
        run: uv run --frozen ty check .

  python_unit_test:
    name: Unit test and code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: Code unit tests
        run: uv run --frozen pytest tests

  toml_lint:
    name: TOML linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: TOML linting check
        run: uv run --frozen taplo lint

  toml_format:
    name: TOML formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: TOML formatting check
        run: uv run --frozen taplo format --diff --check

  yaml_lint:
    name: YAML linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: YAML linting check
        run: uv run --frozen yamllint --format github --strict .

  yaml_format:
    name: YAML format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/environment
      - name: YAML formatting check
        run: uv run --frozen yamlfmt -lint .

  markdown_lint:
    name: Markdown linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: rvben/rumdl@v0
        with:
          command: check

  markdown_format:
    name: Markdown format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: rvben/rumdl@v0
        with:
          command: fmt-check
